remove.packages(c("ggplot2", "data.table"))
install.packages('Rcpp', dependencies = TRUE)
install.packages('ggplot2', dependencies = TRUE)
install.packages('data.table', dependencies = TRUE)
install.packages("taRifx", repos=c("http://rstudio.org/_packages", "http://cran.rstudio.com"))
install.packages(c("doParallel",))
install.packages(c("missForest","C50","caret","doParallel","randomForest"), dependencies = TRUE)
